import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import "./styles/globals.css";
import "./styles/variables.css";
import ThemeToggle from "@/app/components/theme.util";

export const metadata: Metadata = {
  title: "Offy-Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white dark:bg-black">
        <nav className="fixed z-30 w-full border-b bg-white dark:bg-black">
          <div className="px-3 py-3 lg:px-5 lg:pl-3">
            <div className="flex items-center justify-between">
              <a href="/" className="flex ml-2 md:mr-24">
                <div className="h-12 w-12 mr-3">
                  <Image
                    className="rounded-full"
                    src="https://avatars.githubusercontent.com/u/96122242?v=4"
                    width={500}
                    height={500}
                    alt="Logo"
                  />
                </div>
                <h1 className="hidden self-center whitespace-nowrap font-bold text-3xl sm:block lg:text-4xl">
                  Store Management System
                </h1>
              </a>

              <div className="flex items-center">
                <ThemeToggle />
                <div className="h-7 w-7 mr-3 hidden sm:block">
                  <Image
                    className="rounded-full"
                    src="https://avatars.githubusercontent.com/u/96122242?v=10"
                    width={100}
                    height={100}
                    alt="Logo"
                  />
                </div>
              </div>
            </div>
          </div>
        </nav>
        <div className="flex pt-16 overflow-hidden">
          <aside className="hidden fixed top-0 left-0 z-20 flex-col flex-shrink-0 w-64 h-full pt-16 font-normal duration-75  lg:flex transition-width ">
            <div className="relative flex flex-col flex-1 min-h-0 pt-0 border-r">
              <div className="flex flex-col flex-1 pt-5 pb-4 overflow-y-auto">
                <div className="flex-1 px-3 space-y-1">
                  <ul className="pb-2 space-y-2">
                    <li className="flex items-center p-2 text-base rounded-lg">
                      <Link className="flex" href="/">
                        <svg
                          className="mr-2 w-6 h-6 text-gray-500 transition duration-75 group-hover:text-gray-900 dark:text-gray-400 dark:group-hover:text-white"
                          fill="currentColor"
                          viewBox="0 0 20 20"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"></path>
                          <path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"></path>
                        </svg>
                        DASHBOARD
                      </Link>
                    </li>
                    <li className="flex items-center p-2 text-base rounded-lg">
                      <Link className="flex" href="/users">
                        <svg
                          className="mr-2 flex-shrink-0 w-6 h-6 text-gray-500 transition duration-75 group-hover:text-gray-900 dark:text-gray-400 dark:group-hover:text-white"
                          fill="currentColor"
                          viewBox="0 0 20 20"
                          xmlns="http://www.w3.org/2000/svg"
                          aria-hidden="true"
                        >
                          <path
                            clip-rule="evenodd"
                            fill-rule="evenodd"
                            d="M.99 5.24A2.25 2.25 0 013.25 3h13.5A2.25 2.25 0 0119 5.25l.01 9.5A2.25 2.25 0 0116.76 17H3.26A2.267 2.267 0 011 14.74l-.01-9.5zm8.26 9.52v-.625a.75.75 0 00-.75-.75H3.25a.75.75 0 00-.75.75v.615c0 .414.336.75.75.75h5.373a.75.75 0 00.627-.74zm1.5 0a.75.75 0 00.627.74h5.373a.75.75 0 00.75-.75v-.615a.75.75 0 00-.75-.75H11.5a.75.75 0 00-.75.75v.625zm6.75-3.63v-.625a.75.75 0 00-.75-.75H11.5a.75.75 0 00-.75.75v.625c0 .414.336.75.75.75h5.25a.75.75 0 00.75-.75zm-8.25 0v-.625a.75.75 0 00-.75-.75H3.25a.75.75 0 00-.75.75v.625c0 .414.336.75.75.75H8.5a.75.75 0 00.75-.75zM17.5 7.5v-.625a.75.75 0 00-.75-.75H11.5a.75.75 0 00-.75.75V7.5c0 .414.336.75.75.75h5.25a.75.75 0 00.75-.75zm-8.25 0v-.625a.75.75 0 00-.75-.75H3.25a.75.75 0 00-.75.75V7.5c0 .414.336.75.75.75H8.5a.75.75 0 00.75-.75z"
                          ></path>
                        </svg>
                        CUSTOMERS
                      </Link>
                    </li>
                    <li className="flex items-center p-2 text-base rounded-lg">
                      <Link className="flex" href="/products">
                        <svg
                          className="mr-2 flex-shrink-0 w-6 h-6 text-gray-500 transition duration-75 group-hover:text-gray-900 dark:text-gray-400 dark:group-hover:text-white"
                          fill="currentColor"
                          viewBox="0 0 20 20"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path d="M7 3a1 1 0 000 2h6a1 1 0 100-2H7zM4 7a1 1 0 011-1h10a1 1 0 110 2H5a1 1 0 01-1-1zM2 11a2 2 0 012-2h12a2 2 0 012 2v4a2 2 0 01-2 2H4a2 2 0 01-2-2v-4z"></path>
                        </svg>
                        PRODUCTS
                      </Link>
                    </li>
                    <li className="flex items-center p-2 text-base rounded-lg">
                      <Link className="flex" href="/carts">
                        <svg
                          className="mr-2 flex-shrink-0 w-6 h-6 text-gray-500 transition duration-75 group-hover:text-gray-900 dark:text-gray-400 dark:group-hover:text-white"
                          fill="currentColor"
                          viewBox="0 0 20 20"
                          xmlns="http://www.w3.org/2000/svg"
                          aria-hidden="true"
                        >
                          <path d="M3 4a1 1 0 011-1h12a1 1 0 011 1v2a1 1 0 01-1 1H4a1 1 0 01-1-1V4zM3 10a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H4a1 1 0 01-1-1v-6zM14 9a1 1 0 00-1 1v6a1 1 0 001 1h2a1 1 0 001-1v-6a1 1 0 00-1-1h-2z"></path>
                        </svg>
                        ORDERS
                      </Link>
                    </li>
                    <li className="flex items-center p-2 text-base rounded-lg">
                      <Link className="flex" href="/reports">
                        <svg
                          className="mr-2 flex-shrink-0 w-6 h-6 text-gray-500 transition duration-75 group-hover:text-gray-900 dark:text-gray-400 dark:group-hover:text-white"
                          fill="currentColor"
                          viewBox="0 0 20 20"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path d="M9 2a1 1 0 000 2h2a1 1 0 100-2H9z"></path>
                          <path
                            fill-rule="evenodd"
                            d="M4 5a2 2 0 012-2 3 3 0 003 3h2a3 3 0 003-3 2 2 0 012 2v11a2 2 0 01-2 2H6a2 2 0 01-2-2V5zm3 4a1 1 0 000 2h.01a1 1 0 100-2H7zm3 0a1 1 0 000 2h3a1 1 0 100-2h-3zm-3 4a1 1 0 100 2h.01a1 1 0 100-2H7zm3 0a1 1 0 100 2h3a1 1 0 100-2h-3z"
                            clip-rule="evenodd"
                          ></path>
                        </svg>
                        REPORT
                      </Link>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </aside>
          <div className="relative w-full h-full overflow-y-auto lg:ml-64 ">
            <main>
              <div className="px-4 pt-6 bg-slate-100 dark:bg-indigo-950/50">
                <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-4">
                  {children}
                </div>
              </div>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
